MDEV-25292 Atomic CREATE OR REPLACE TABLE
High level operation

  Two DDL chains are used for CREATE OR REPLACE execution:
  ddl_log_state_create (C) and ddl_log_state_rm (D).

  1. (C) Write DDL_LOG_RENAME_TABLE_ACTION from normal to backup;
  2. Rename table from normal to backup;
  3. D is replayed only if C is closed (D is linked as a slave to C);
  4. (D) Write DDL_LOG_DROP_ACTION of backup;
  5. (C) Write DDL_LOG_CREATE_TABLE_ACTION of new table;
  6. Create new table;
  7. (C) update XID;

  (In case of success)
  8. (C) close chain;
  9. (D) replay chain.

  (In case of error)
  8. (C) replay chain;
  9. (D) close chain.

Backup table for CREATE OR REPLACE

  - Instead of dropping the table, CREATE OR REPLACE renames table to
    a backup name. The rename is written into ddl_log_state_create.

  - CREATE TABLE without REPLACE is not affected by this commit.

  - Engines having HTON_EXPENSIVE_RENAME flag set are not affected by
    this commit.

  - The backup is done inside mysql_rm_table_no_locks() to be able to
    support ATOMIC DROP TABLE of multiple tables.

  - The ddl logging of CREATE and DROP are linked together. CREATE
    entries are executed before DROP entries.

  - In case of failed CREATE OR REPLACE ddl_log_state_create is
    replayed which restores original table.

  - In case of succeeded CREATE OR REPLACE ddl_log_state_rm is
    replayed which drops the backup (original table).

  - CREATE TABLE .. SELECT XID usage is fixed and now there is no need
    to log DROP TABLE via DDL_CREATE_TABLE_PHASE_LOG (see comments in
    do_postlock()). XID is now correctly updated so it disables
    DDL_LOG_DROP_TABLE_ACTION. Note that binary log is flushed at the
    final stage when the table is ready. So if we have XID in the
    binary log we don't need to drop the table.

  - Three variations of CREATE OR REPLACE handled:

    1. CREATE OR REPLACE TABLE t1 (..);
    2. CREATE OR REPLACE TABLE t1 LIKE t2;
    3. CREATE OR REPLACE TABLE t1 SELECT ..;

  - Test case uses 5 combinations for engines (aria, aria_notrans,
    myisam, ib, expensive_rename) and 2 combinations for binlog types
    (row, stmt). Combinations help to check differences between the
    results. Error failures are tested for the above three variations.

  - Triggers mechanism is unaffected by this change. This is tested in
    create_replace.test.

  - Triggers mechanism is unaffected which is tested.

  - LOCK TABLES is affected because RENAME TABLE cannot work on locked
    table. mysql_do_rename() (original do_rename()) can now work under
    locked_tables_mode.

On XID usage

  Like with all other atomic DDL operations XID is used to avoid
  inconsistency between master and slave in the case of a crash after
  binary log is written and before ddl_log_state_create is closed. On
  recovery XIDs are taken from binary log and corresponding DDL log
  events get disabled.  That is done by
  ddl_log_close_binlogged_events().

On linking two chains together

  Chains are executed in the ascending order of entry_pos of execute
  entries. But entry_pos assignment order is undefined: it may assign
  bigger number for the first chain and then smaller number for the
  second chain. So the execution order in that case will be reverse:
  second chain will be executed first.

MDEV-25292 Refactoring: moved select_field_count into Alter_info.

There is a need in MDEV-25292 to have both C_ALTER_TABLE and
select_field_count in one call. Semantically creation mode and field
count are two different things. Making creation mode negative
constants and field count positive variable into one parameter seems
to be a lazy hack for not making the second parameter.

select_field_count does not make sense without
alter_info->select_field_count, so the natural way is to hold it in
Alter_info too.

Revert "Moved rename logic to create_table_no_lock()"

This reverts commit b1ef4d5f75f22c5f85eec74bd8bf09f924b01844.

CREATE .. SELECT has to rename back after the copy process, not in
create_table_no_lock().

CREATE .. SELECT: tmp table created

Use create_and_open_tmp_table() like in ALTER TABLE to create
temporary TABLE object (tmp_table == (NON_)TRANSACTIONAL_TMP_TABLE).

After we credated such TABLE we cannot use create_info->tmp_table() as
it checks only parser-requested tmp-table. Instead we check
table->s->tmp_table.

Rename and drop via DDL log

We replay ddl_log_state_rm to drop the old table and rename the
temporary table. In that case we must throw the correct error message
if ddl_log_revert() fails (f.ex. on FK error).

If table is deleted earlier and not via DDL log and the crash
happened, your create chain is not closed. Linked drop chain is not
executed and the new table is not installed. But the old table is
already deleted.

ddl_log.cc changes

Now we can place action before DDL_LOG_DROP_INIT_ACTION and it will be
replayed after DDL_LOG_DROP_TABLE_ACTION.

ddl_log_execute_action() now prints error message if it is not
executed from recovery (checked by ddl_log_recovery()).

MDEV-22166 ddl_log_write_execute_entry() extension

Don't execute this chain if cond_entry chain is active.

CREATE SELECT fixes

External locking is required for temporary table created by
create_and_open_tmp_table(). F.ex. that disables logging for Aria
transactional tables and wihout that (when no mysql_lock_tables() is
done) it cannot work correctly.

Before external locking transactions must be disabled by
ha_enable_transaction(false). Both locking and transactions must be
reenabled before rename from temporary table.

MDEV-27048 UBSAN: runtime error: shift exponent 32 is too large for 32-bit type 'unsigned int'

32-bit variable must be expanded to 64-bit before shift left.

HA_OPEN_INTERNAL_TABLE reverted

We cannot add that flag because test_if_reopen() is not called:

  if (!internal_table)
  {
    mysql_mutex_lock(&THR_LOCK_myisam);
    old_info= test_if_reopen(name_buff);
  }

A new share is created for every HA_OPEN_INTERNAL_TABLE and duplicate
errors are missed because insert and lookup is done via 2 different
handlers (see create_lookup_handler()).

long_unique_bugs fixed!

Without ha_reset() the data is lost (as well as stats, etc). That is
done by mark_tmp_table_as_free_for_reuse().

ha_reset() also releases MYISAM_SHARE. Without that share is
kept and second CREATE OR REPLACE .. SELECT fails with

HA_ERR_TABLE_EXIST (156): MyISAM table '#sql-create-b5377-4-t2' is in
use (most likely by a MERGE table). Try FLUSH TABLES.

HA_EXTRA_PREPARE_FOR_DROP also removes MYISAM_SHARE, but that is not
needed as ha_reset() does the job.

Atomic_replace_info refactoring